### Test API Località

# Test endpoint GetLocations
GET https://localhost:7267/api/Generic/GetLocations
Content-Type: application/json

###

# Test endpoint GetHomeDetails
GET https://localhost:7267/api/Generic/GetHomeDetails
Content-Type: application/json

###

# Test endpoint GetPropertyCount
GET https://localhost:7267/api/RealEstateProperty/GetPropertyCount
Content-Type: application/json

### 